"use client";

import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "ja" | "en" | "ko" | "vi" | "zh" | "es";

export const LANG_LABELS: Record<Lang, string> = {
  ja: "日本語",
  en: "English",
  ko: "한국어",
  vi: "Tiếng Việt",
  zh: "中文",
  es: "Español",
};

export const LANG_FLAGS: Record<Lang, string> = {
  ja: "🇯🇵",
  en: "🇺🇸",
  ko: "🇰🇷",
  vi: "🇻🇳",
  zh: "🇨🇳",
  es: "🇨🇴",
};

export const T: Record<Lang, Record<string, string>> = {
  ja: {
    // Nav
    dashboard: "ダッシュボード",
    attendance: "勤怠管理",
    okr: "OKR",
    team: "チーム",
    global: "グローバル",
    settings: "設定",
    notifications: "通知設定",
    // Status
    present: "出勤中",
    remote: "在宅勤務",
    leave: "有給休暇",
    absent: "未打刻",
    present_short: "出勤",
    remote_short: "在宅",
    leave_short: "有休",
    absent_short: "未打刻",
    overtime_short: "残業",
    // Dashboard
    greeting: "おはようございます",
    realtime: "リアルタイム",
    team_attendance: "チーム勤怠状況",
    ai_insights: "AI インサイト",
    member: "メンバー",
    status: "ステータス",
    overtime: "今月残業",
    remaining_leave: "残有給",
    team_members_of: "チームメンバー",
    of_count: "名中",
    days_unit: "日",
    schedule_1on1: "1on1をスケジュール →",
    encourage_leave_link: "有給取得を促進 →",
    view_details: "詳細を見る →",
    // OKR page
    okr_mgmt: "OKR 管理",
    okr_subtitle: "Q2 2026 · 目標と主要成果の進捗管理",
    add_okr: "+ OKRを追加",
    company_okr: "🏢 全社 OKR",
    team_okr: "👥 チーム OKR",
    individual_okr: "👤 個人 OKR",
    overall_progress: "総合進捗",
    attendance_linked: "勤怠データ連動 —",
    actual: "実績",
    usage_rate: "消化率",
    add_individual_okr: "個人OKRを追加 — メンバーを選択して目標を設定",
    no_okr_set: "OKR未設定",
    set_okr: "+ 設定する",
    // OKR status
    on_track: "順調",
    at_risk: "要注意",
    off_track: "要改善",
    // Team page
    team_detail: "チーム詳細",
    team_subtitle: "メンバーの勤怠 × OKR 統合ビュー",
    this_month_sick: "病欠（今月）",
    okr_progress: "OKR進捗",
    // Attendance page
    attendance_mgmt: "勤怠管理",
    attendance_subtitle: "チームの出退勤・有給残日数を管理",
    attendance_calendar: "勤怠カレンダー",
    leave_balance: "有給残日数",
    weekly_attendance: "週次勤怠",
    monthly_overtime: "今月残業",
    pending_approvals: "承認待ち申請",
    leave_usage_rate: "有給消化率",
    days_remaining: "残日数",
    sick_leave: "病欠",
    encourage_leave: "取得促進",
    filter: "フィルター",
    export_csv: "CSV出力",
    // Global page
    global_view: "グローバル統合ビュー",
    global_subtitle: "5カ国 · 250名 · 2026年6月",
    headcount: "社員数",
    attendance_rate: "出勤率",
    avg_overtime: "平均残業",
    leave_rate: "有給消化率",
    compliance_alert_label: "法令アラート",
    compliance_alerts_unit: "件",
    compliance_title: "コンプライアンスアラート",
    monthly_overtime_trend: "月次平均残業時間（拠点別推移）",
    ai_analysis: "AI分析 — 人員配置インサイト",
    ai_analysis_sub: "勤怠データ × OKR達成率 から算出した組織への提言",
    view_detail_arrow: "詳細を見る →",
    // Settings
    language: "表示言語",
    timezone: "タイムゾーン",
    notification_settings: "通知設定",
    profile: "プロフィール",
    save: "保存",
    approve: "承認",
    reject: "却下",
    team_health: "チーム健康サマリー",
    wearable_sync: "ウェアラブル連携",
    no_device: "デバイス未連携",
    health_alert: "要確認",
    normal: "正常",
    // Notification panel
    notif_btn: "通知",
    unread_count: "未読",
    unread_unit: "件",
    mark_all_read: "すべて既読",
    no_notifications: "通知はありません",
    notif_settings_link: "通知設定を変更 →",
    // My page
    punch_section: "打刻",
    punch_in: "出勤打刻",
    punch_out: "退勤打刻",
    punched_in_at: "出勤中 — 打刻時刻",
    punched_out_at: "退勤しました。お疲れ様でした！👋",
    manual_edit: "手動修正",
    health_saved: "保存しました",
    leave_section: "休暇申請",
    remaining_leave_label: "残有給",
    apply_leave_btn: "申請する",
    leave_submitted_msg: "申請を送信しました。承認をお待ちください。",
    leave_type_label: "種別",
    leave_from_label: "開始日",
    leave_to_label: "終了日",
    leave_reason_label: "理由（任意）",
    leave_submit_btn: "申請を送る",
    cancel_btn: "キャンセル",
    leave_annual: "有給休暇",
    leave_sick_opt: "病欠",
    leave_special: "特別休暇",
    leave_half: "半日休暇",
    wellness_title: "体調チャット",
    admin_only_label: "管理者・本人のみ閲覧",
    chat_placeholder: "体調や気になることを入力…",
    proof_label: "修正の根拠（スクリーンショット・医師証明書など）",
    upload_btn: "ファイルをアップロード",
    // Bot responses
    bot_greeting: "こんにちは。体調や気になることがあれば気軽に話しかけてください。この会話はあなたと管理者のみ確認できます。🔒",
    bot_headache: "頭痛のご連絡ありがとうございます。無理せず早退や在宅勤務も検討してください。必要であれば人事へご相談いただけます。",
    bot_fever: "発熱の症状がある場合、出社を控えることをお勧めします。体温を記録し、必要に応じて医療機関を受診してください。",
    bot_tired: "お疲れ様です。睡眠不足が続くと健康に影響が出やすいです。上長に状況を共有することも一つの選択肢です。",
    bot_stress: "お気持ちを打ち明けてくださりありがとうございます。必要であれば1on1を設定することもできますので、お気軽にご相談ください。",
    bot_ok: "それは良かったです！今日も無理せず、体調に変化があればいつでもこちらへ。",
    bot_default: "ご連絡ありがとうございます。内容を確認しました。体調に大きな変化があれば、早めに管理者や医療機関へご相談ください。",
  },
  en: {
    dashboard: "Dashboard",
    attendance: "Attendance",
    okr: "OKR",
    team: "Team",
    global: "Global",
    settings: "Settings",
    notifications: "Notifications",
    present: "In office",
    remote: "Remote",
    leave: "On leave",
    absent: "Not punched",
    present_short: "Present",
    remote_short: "Remote",
    leave_short: "Leave",
    absent_short: "Absent",
    overtime_short: "Overtime",
    greeting: "Good morning",
    realtime: "Real-time",
    team_attendance: "Team Attendance",
    ai_insights: "AI Insights",
    member: "Member",
    status: "Status",
    overtime: "Overtime (mo.)",
    remaining_leave: "Leave left",
    team_members_of: "Team members",
    of_count: "of",
    days_unit: "d",
    schedule_1on1: "Schedule 1-on-1 →",
    encourage_leave_link: "Encourage leave →",
    view_details: "View details →",
    okr_mgmt: "OKR Management",
    okr_subtitle: "Q2 2026 · Track objectives and key results",
    add_okr: "+ Add OKR",
    company_okr: "🏢 Company OKR",
    team_okr: "👥 Team OKR",
    individual_okr: "👤 Individual OKR",
    overall_progress: "Overall progress",
    attendance_linked: "Attendance-linked —",
    actual: "Actual",
    usage_rate: "Usage",
    add_individual_okr: "Add individual OKR — select a member to set goals",
    no_okr_set: "No OKR set",
    set_okr: "+ Set up",
    on_track: "On track",
    at_risk: "At risk",
    off_track: "Off track",
    team_detail: "Team Details",
    team_subtitle: "Attendance × OKR integrated view per member",
    this_month_sick: "Sick days (mo.)",
    okr_progress: "OKR Progress",
    attendance_mgmt: "Attendance",
    attendance_subtitle: "Manage team check-ins and leave balances",
    attendance_calendar: "Attendance Calendar",
    leave_balance: "Leave Balance",
    weekly_attendance: "Weekly Attendance",
    monthly_overtime: "Overtime (month)",
    pending_approvals: "Pending Approvals",
    leave_usage_rate: "Leave usage",
    days_remaining: "Remaining",
    sick_leave: "Sick leave",
    encourage_leave: "Encourage leave",
    filter: "Filter",
    export_csv: "Export CSV",
    global_view: "Global Overview",
    global_subtitle: "5 countries · 250 people · June 2026",
    headcount: "Headcount",
    attendance_rate: "Attendance",
    avg_overtime: "Avg overtime",
    leave_rate: "Leave usage",
    compliance_alert_label: "Compliance alert",
    compliance_alerts_unit: "",
    compliance_title: "Compliance Alerts",
    monthly_overtime_trend: "Monthly avg overtime by location",
    ai_analysis: "AI Analysis — Workforce Insights",
    ai_analysis_sub: "Recommendations derived from attendance × OKR achievement data",
    view_detail_arrow: "View details →",
    language: "Display language",
    timezone: "Timezone",
    notification_settings: "Notification Settings",
    profile: "Profile",
    save: "Save",
    approve: "Approve",
    reject: "Reject",
    team_health: "Team Health Summary",
    wearable_sync: "Wearable sync",
    no_device: "No device",
    health_alert: "Alert",
    normal: "Normal",
    notif_btn: "Notifications",
    unread_count: "Unread",
    unread_unit: "",
    mark_all_read: "Mark all read",
    no_notifications: "No notifications",
    notif_settings_link: "Notification settings →",
    punch_section: "Check-in",
    punch_in: "Punch In",
    punch_out: "Punch Out",
    punched_in_at: "In office — punched in at",
    punched_out_at: "Punched out. Have a good rest! 👋",
    manual_edit: "Edit manually",
    health_saved: "Saved",
    leave_section: "Leave Request",
    remaining_leave_label: "Remaining leave",
    apply_leave_btn: "Request",
    leave_submitted_msg: "Request submitted. Awaiting approval.",
    leave_type_label: "Type",
    leave_from_label: "From",
    leave_to_label: "To",
    leave_reason_label: "Reason (optional)",
    leave_submit_btn: "Submit",
    cancel_btn: "Cancel",
    leave_annual: "Annual leave",
    leave_sick_opt: "Sick leave",
    leave_special: "Special leave",
    leave_half: "Half day",
    wellness_title: "Wellness Chat",
    admin_only_label: "Visible to admin & you only",
    chat_placeholder: "How are you feeling today?",
    proof_label: "Proof (screenshot, doctor's note, etc.)",
    upload_btn: "Upload file",
    bot_greeting: "Hello! Feel free to share how you're feeling. This conversation is only visible to you and your manager. 🔒",
    bot_headache: "Thank you for letting me know. Please consider working from home or leaving early if needed. Feel free to reach out to HR.",
    bot_fever: "If you have a fever, please avoid coming to the office. Record your temperature and see a doctor if necessary.",
    bot_tired: "Thank you for sharing. Lack of sleep can affect your health. Consider letting your manager know about your situation.",
    bot_stress: "Thank you for opening up. You can schedule a 1-on-1 with your manager anytime — don't hesitate to reach out.",
    bot_ok: "Glad to hear that! Take care, and feel free to check in anytime.",
    bot_default: "Thank you for reaching out. If your condition changes significantly, please consult your manager or a medical professional.",
  },
  ko: {
    dashboard: "대시보드",
    attendance: "근태 관리",
    okr: "OKR",
    team: "팀",
    global: "글로벌",
    settings: "설정",
    notifications: "알림 설정",
    present: "출근 중",
    remote: "재택근무",
    leave: "유급 휴가",
    absent: "미출근",
    present_short: "출근",
    remote_short: "재택",
    leave_short: "휴가",
    absent_short: "미출근",
    overtime_short: "잔업",
    greeting: "좋은 아침입니다",
    realtime: "실시간",
    team_attendance: "팀 근태 현황",
    ai_insights: "AI 인사이트",
    member: "멤버",
    status: "상태",
    overtime: "이번 달 잔업",
    remaining_leave: "잔여 휴가",
    team_members_of: "팀 멤버",
    of_count: "명 중",
    days_unit: "일",
    schedule_1on1: "1on1 예약하기 →",
    encourage_leave_link: "휴가 촉진하기 →",
    view_details: "자세히 보기 →",
    okr_mgmt: "OKR 관리",
    okr_subtitle: "Q2 2026 · 목표 및 핵심 결과 진행 관리",
    add_okr: "+ OKR 추가",
    company_okr: "🏢 전사 OKR",
    team_okr: "👥 팀 OKR",
    individual_okr: "👤 개인 OKR",
    overall_progress: "종합 진행률",
    attendance_linked: "근태 데이터 연동 —",
    actual: "실적",
    usage_rate: "사용률",
    add_individual_okr: "개인 OKR 추가 — 멤버를 선택하여 목표 설정",
    no_okr_set: "OKR 미설정",
    set_okr: "+ 설정하기",
    on_track: "순조로움",
    at_risk: "주의 필요",
    off_track: "개선 필요",
    team_detail: "팀 상세",
    team_subtitle: "멤버별 근태 × OKR 통합 뷰",
    this_month_sick: "병가 (이번 달)",
    okr_progress: "OKR 진행률",
    attendance_mgmt: "근태 관리",
    attendance_subtitle: "팀 출퇴근 및 휴가 잔여일 관리",
    attendance_calendar: "근태 캘린더",
    leave_balance: "휴가 잔여",
    weekly_attendance: "주간 근태",
    monthly_overtime: "이달 잔업",
    pending_approvals: "승인 대기",
    leave_usage_rate: "휴가 사용률",
    days_remaining: "잔여",
    sick_leave: "병가",
    encourage_leave: "휴가 촉진",
    filter: "필터",
    export_csv: "CSV 내보내기",
    global_view: "글로벌 통합 뷰",
    global_subtitle: "5개국 · 250명 · 2026년 6월",
    headcount: "인원",
    attendance_rate: "출근율",
    avg_overtime: "평균 잔업",
    leave_rate: "휴가 사용률",
    compliance_alert_label: "법령 알림",
    compliance_alerts_unit: "건",
    compliance_title: "컴플라이언스 알림",
    monthly_overtime_trend: "월별 평균 잔업 시간 (거점별 추이)",
    ai_analysis: "AI 분석 — 인력 배치 인사이트",
    ai_analysis_sub: "근태 데이터 × OKR 달성률로 산출한 조직 제언",
    view_detail_arrow: "자세히 보기 →",
    language: "표시 언어",
    timezone: "시간대",
    notification_settings: "알림 설정",
    profile: "프로필",
    save: "저장",
    approve: "승인",
    reject: "거부",
    team_health: "팀 건강 요약",
    wearable_sync: "웨어러블 연동",
    no_device: "기기 없음",
    health_alert: "확인 필요",
    normal: "정상",
    notif_btn: "알림",
    unread_count: "읽지 않음",
    unread_unit: "개",
    mark_all_read: "모두 읽음",
    no_notifications: "알림이 없습니다",
    notif_settings_link: "알림 설정 →",
    punch_section: "출퇴근 기록",
    punch_in: "출근 기록",
    punch_out: "퇴근 기록",
    punched_in_at: "출근 중 — 기록 시각",
    punched_out_at: "퇴근 완료. 수고하셨습니다! 👋",
    manual_edit: "수동 수정",
    health_saved: "저장되었습니다",
    leave_section: "휴가 신청",
    remaining_leave_label: "잔여 휴가",
    apply_leave_btn: "신청하기",
    leave_submitted_msg: "신청이 제출되었습니다. 승인을 기다려 주세요.",
    leave_type_label: "종류",
    leave_from_label: "시작일",
    leave_to_label: "종료일",
    leave_reason_label: "사유 (선택)",
    leave_submit_btn: "제출하기",
    cancel_btn: "취소",
    leave_annual: "연차 휴가",
    leave_sick_opt: "병가",
    leave_special: "특별 휴가",
    leave_half: "반차",
    wellness_title: "건강 채팅",
    admin_only_label: "관리자·본인만 열람 가능",
    chat_placeholder: "오늘 컨디션이 어떠세요?",
    proof_label: "수정 근거 (스크린샷, 진단서 등)",
    upload_btn: "파일 업로드",
    bot_greeting: "안녕하세요! 컨디션이나 걱정되는 점이 있으면 편하게 말씀해 주세요. 이 대화는 본인과 관리자만 확인할 수 있습니다. 🔒",
    bot_headache: "두통 증상을 알려주셔서 감사합니다. 무리하지 마시고 재택근무나 조기 퇴근도 고려해 보세요. 필요하면 인사팀에 상담하세요.",
    bot_fever: "발열 증상이 있으면 출근을 자제하는 것을 권장합니다. 체온을 기록하고 필요시 의료기관을 방문해 주세요.",
    bot_tired: "고생하셨습니다. 수면 부족이 지속되면 건강에 영향을 줄 수 있습니다. 상황을 상사에게 공유하는 것도 좋은 방법입니다.",
    bot_stress: "솔직하게 말씀해 주셔서 감사합니다. 필요하면 1on1 미팅을 설정할 수도 있으니 언제든지 연락해 주세요.",
    bot_ok: "다행입니다! 오늘도 무리하지 마시고, 변화가 있으면 언제든 알려주세요.",
    bot_default: "연락해 주셔서 감사합니다. 컨디션에 큰 변화가 있으면 관리자나 의료기관에 상담해 주세요.",
  },
  vi: {
    dashboard: "Tổng quan",
    attendance: "Chấm công",
    okr: "OKR",
    team: "Nhóm",
    global: "Toàn cầu",
    settings: "Cài đặt",
    notifications: "Thông báo",
    present: "Đang làm việc",
    remote: "Làm việc từ xa",
    leave: "Nghỉ phép",
    absent: "Chưa chấm công",
    present_short: "Có mặt",
    remote_short: "Từ xa",
    leave_short: "Nghỉ phép",
    absent_short: "Vắng mặt",
    overtime_short: "Tăng ca",
    greeting: "Chào buổi sáng",
    realtime: "Thời gian thực",
    team_attendance: "Chấm công nhóm",
    ai_insights: "AI Insights",
    member: "Thành viên",
    status: "Trạng thái",
    overtime: "Tăng ca (tháng)",
    remaining_leave: "Phép còn lại",
    team_members_of: "Thành viên nhóm",
    of_count: "trong",
    days_unit: "ngày",
    schedule_1on1: "Lên lịch 1-on-1 →",
    encourage_leave_link: "Khuyến khích nghỉ phép →",
    view_details: "Xem chi tiết →",
    okr_mgmt: "Quản lý OKR",
    okr_subtitle: "Q2 2026 · Theo dõi mục tiêu và kết quả then chốt",
    add_okr: "+ Thêm OKR",
    company_okr: "🏢 OKR Công ty",
    team_okr: "👥 OKR Nhóm",
    individual_okr: "👤 OKR Cá nhân",
    overall_progress: "Tiến độ tổng thể",
    attendance_linked: "Liên kết chấm công —",
    actual: "Thực tế",
    usage_rate: "Tỷ lệ",
    add_individual_okr: "Thêm OKR cá nhân — chọn thành viên để đặt mục tiêu",
    no_okr_set: "Chưa có OKR",
    set_okr: "+ Thiết lập",
    on_track: "Đúng tiến độ",
    at_risk: "Cần chú ý",
    off_track: "Cần cải thiện",
    team_detail: "Chi tiết nhóm",
    team_subtitle: "Chấm công × OKR tích hợp theo từng thành viên",
    this_month_sick: "Nghỉ bệnh (tháng)",
    okr_progress: "Tiến độ OKR",
    attendance_mgmt: "Chấm công",
    attendance_subtitle: "Quản lý giờ làm và phép của nhóm",
    attendance_calendar: "Lịch chấm công",
    leave_balance: "Phép còn lại",
    weekly_attendance: "Chấm công tuần",
    monthly_overtime: "Tăng ca (tháng)",
    pending_approvals: "Chờ phê duyệt",
    leave_usage_rate: "Tỷ lệ nghỉ phép",
    days_remaining: "Còn lại",
    sick_leave: "Nghỉ bệnh",
    encourage_leave: "Khuyến khích nghỉ",
    filter: "Lọc",
    export_csv: "Xuất CSV",
    global_view: "Tổng quan toàn cầu",
    global_subtitle: "5 quốc gia · 250 người · Tháng 6/2026",
    headcount: "Nhân sự",
    attendance_rate: "Tỷ lệ đi làm",
    avg_overtime: "Tăng ca TB",
    leave_rate: "Tỷ lệ nghỉ phép",
    compliance_alert_label: "Cảnh báo tuân thủ",
    compliance_alerts_unit: "",
    compliance_title: "Cảnh báo tuân thủ pháp luật",
    monthly_overtime_trend: "Tăng ca trung bình theo tháng (theo chi nhánh)",
    ai_analysis: "Phân tích AI — Insight nhân lực",
    ai_analysis_sub: "Khuyến nghị từ dữ liệu chấm công × tỷ lệ đạt OKR",
    view_detail_arrow: "Xem chi tiết →",
    language: "Ngôn ngữ hiển thị",
    timezone: "Múi giờ",
    notification_settings: "Cài đặt thông báo",
    profile: "Hồ sơ",
    save: "Lưu",
    approve: "Duyệt",
    reject: "Từ chối",
    team_health: "Sức khỏe nhóm",
    wearable_sync: "Đồng bộ thiết bị",
    no_device: "Chưa kết nối",
    health_alert: "Cảnh báo",
    normal: "Bình thường",
    notif_btn: "Thông báo",
    unread_count: "Chưa đọc",
    unread_unit: "",
    mark_all_read: "Đánh dấu tất cả đã đọc",
    no_notifications: "Không có thông báo",
    notif_settings_link: "Cài đặt thông báo →",
    punch_section: "Chấm công",
    punch_in: "Vào làm",
    punch_out: "Ra về",
    punched_in_at: "Đang làm — chấm công lúc",
    punched_out_at: "Đã ra về. Nghỉ ngơi nhé! 👋",
    manual_edit: "Chỉnh sửa thủ công",
    health_saved: "Đã lưu",
    leave_section: "Xin nghỉ phép",
    remaining_leave_label: "Phép còn lại",
    apply_leave_btn: "Xin nghỉ",
    leave_submitted_msg: "Đã gửi yêu cầu. Vui lòng chờ phê duyệt.",
    leave_type_label: "Loại",
    leave_from_label: "Từ ngày",
    leave_to_label: "Đến ngày",
    leave_reason_label: "Lý do (tùy chọn)",
    leave_submit_btn: "Gửi yêu cầu",
    cancel_btn: "Hủy",
    leave_annual: "Nghỉ phép năm",
    leave_sick_opt: "Nghỉ ốm",
    leave_special: "Nghỉ đặc biệt",
    leave_half: "Nửa ngày",
    wellness_title: "Chat sức khỏe",
    admin_only_label: "Chỉ quản lý & bạn xem được",
    chat_placeholder: "Hôm nay bạn cảm thấy thế nào?",
    proof_label: "Bằng chứng (ảnh chụp màn hình, giấy bác sĩ…)",
    upload_btn: "Tải file lên",
    bot_greeting: "Xin chào! Hãy chia sẻ nếu bạn cảm thấy không khỏe. Cuộc trò chuyện này chỉ bạn và quản lý mới thấy. 🔒",
    bot_headache: "Cảm ơn bạn đã chia sẻ. Hãy cân nhắc làm việc tại nhà hoặc về sớm nếu cần. Liên hệ HR nếu muốn hỗ trợ.",
    bot_fever: "Nếu có sốt, hãy tránh đến văn phòng. Ghi lại nhiệt độ và gặp bác sĩ nếu cần thiết.",
    bot_tired: "Cảm ơn bạn đã chia sẻ. Thiếu ngủ kéo dài ảnh hưởng đến sức khỏe. Hãy thông báo cho quản lý về tình trạng của bạn.",
    bot_stress: "Cảm ơn bạn đã tâm sự. Bạn có thể đặt lịch 1-on-1 bất cứ lúc nào — đừng ngần ngại.",
    bot_ok: "Thật vui khi nghe vậy! Hãy giữ gìn sức khỏe và liên hệ bất cứ khi nào cần.",
    bot_default: "Cảm ơn bạn đã liên hệ. Nếu tình trạng thay đổi đáng kể, hãy tham khảo ý kiến quản lý hoặc bác sĩ.",
  },
  zh: {
    dashboard: "仪表盘",
    attendance: "考勤管理",
    okr: "OKR",
    team: "团队",
    global: "全球",
    settings: "设置",
    notifications: "通知设置",
    present: "在职",
    remote: "远程办公",
    leave: "请假",
    absent: "未打卡",
    present_short: "在勤",
    remote_short: "远程",
    leave_short: "休假",
    absent_short: "未打卡",
    overtime_short: "加班",
    greeting: "早上好",
    realtime: "实时",
    team_attendance: "团队考勤",
    ai_insights: "AI 洞察",
    member: "成员",
    status: "状态",
    overtime: "本月加班",
    remaining_leave: "剩余假期",
    team_members_of: "团队成员",
    of_count: "共",
    days_unit: "天",
    schedule_1on1: "安排1on1 →",
    encourage_leave_link: "促进休假 →",
    view_details: "查看详情 →",
    okr_mgmt: "OKR 管理",
    okr_subtitle: "Q2 2026 · 目标与关键成果进度管理",
    add_okr: "+ 添加 OKR",
    company_okr: "🏢 全司 OKR",
    team_okr: "👥 团队 OKR",
    individual_okr: "👤 个人 OKR",
    overall_progress: "综合进度",
    attendance_linked: "考勤数据关联 —",
    actual: "实绩",
    usage_rate: "使用率",
    add_individual_okr: "添加个人OKR — 选择成员设定目标",
    no_okr_set: "未设置OKR",
    set_okr: "+ 设置",
    on_track: "顺利",
    at_risk: "需关注",
    off_track: "需改善",
    team_detail: "团队详情",
    team_subtitle: "成员考勤 × OKR 综合视图",
    this_month_sick: "病假（本月）",
    okr_progress: "OKR进度",
    attendance_mgmt: "考勤管理",
    attendance_subtitle: "管理团队打卡与假期余额",
    attendance_calendar: "考勤日历",
    leave_balance: "剩余假期",
    weekly_attendance: "本周考勤",
    monthly_overtime: "本月加班",
    pending_approvals: "待审批",
    leave_usage_rate: "假期使用率",
    days_remaining: "剩余",
    sick_leave: "病假",
    encourage_leave: "鼓励休假",
    filter: "筛选",
    export_csv: "导出 CSV",
    global_view: "全球综合视图",
    global_subtitle: "5个国家 · 250人 · 2026年6月",
    headcount: "人数",
    attendance_rate: "出勤率",
    avg_overtime: "平均加班",
    leave_rate: "假期使用率",
    compliance_alert_label: "合规警报",
    compliance_alerts_unit: "件",
    compliance_title: "合规警报",
    monthly_overtime_trend: "各据点月均加班时间趋势",
    ai_analysis: "AI分析 — 人力配置洞察",
    ai_analysis_sub: "基于考勤数据 × OKR达成率的组织建议",
    view_detail_arrow: "查看详情 →",
    language: "显示语言",
    timezone: "时区",
    notification_settings: "通知设置",
    profile: "个人资料",
    save: "保存",
    approve: "批准",
    reject: "拒绝",
    team_health: "团队健康摘要",
    wearable_sync: "可穿戴设备同步",
    no_device: "未连接设备",
    health_alert: "需关注",
    normal: "正常",
    notif_btn: "通知",
    unread_count: "未读",
    unread_unit: "条",
    mark_all_read: "全部标为已读",
    no_notifications: "暂无通知",
    notif_settings_link: "通知设置 →",
    punch_section: "打卡",
    punch_in: "上班打卡",
    punch_out: "下班打卡",
    punched_in_at: "在岗中 — 打卡时间",
    punched_out_at: "已下班打卡。辛苦了！👋",
    manual_edit: "手动修正",
    health_saved: "已保存",
    leave_section: "请假申请",
    remaining_leave_label: "剩余假期",
    apply_leave_btn: "申请",
    leave_submitted_msg: "申请已提交，请等待审批。",
    leave_type_label: "类型",
    leave_from_label: "开始日期",
    leave_to_label: "结束日期",
    leave_reason_label: "原因（选填）",
    leave_submit_btn: "提交申请",
    cancel_btn: "取消",
    leave_annual: "年假",
    leave_sick_opt: "病假",
    leave_special: "特殊假",
    leave_half: "半天假",
    wellness_title: "健康聊天",
    admin_only_label: "仅管理员与本人可见",
    chat_placeholder: "今天感觉怎么样？",
    proof_label: "修正依据（截图、医生证明等）",
    upload_btn: "上传文件",
    bot_greeting: "你好！如有身体不适或困扰，请随时告知。此对话仅你和管理员可见。🔒",
    bot_headache: "感谢告知头痛情况。请考虑居家办公或提前下班。如需帮助，请联系人事部门。",
    bot_fever: "如有发烧症状，请避免到公司上班。请记录体温，必要时就医。",
    bot_tired: "辛苦了。长期睡眠不足会影响健康。建议将情况告知上级。",
    bot_stress: "感谢您的坦诚。可以随时安排1对1谈话，请不要犹豫。",
    bot_ok: "太好了！注意休息，有任何变化随时联系我。",
    bot_default: "感谢联系。如身体状况有明显变化，请咨询管理员或医疗专业人员。",
  },
  es: {
    dashboard: "Panel",
    attendance: "Asistencia",
    okr: "OKR",
    team: "Equipo",
    global: "Global",
    settings: "Configuración",
    notifications: "Notificaciones",
    present: "En oficina",
    remote: "Remoto",
    leave: "Permiso",
    absent: "Sin registrar",
    present_short: "Presente",
    remote_short: "Remoto",
    leave_short: "Permiso",
    absent_short: "Sin registrar",
    overtime_short: "Extra",
    greeting: "Buenos días",
    realtime: "Tiempo real",
    team_attendance: "Asistencia del equipo",
    ai_insights: "Perspectivas de IA",
    member: "Miembro",
    status: "Estado",
    overtime: "Horas extra (mes)",
    remaining_leave: "Días restantes",
    team_members_of: "Miembros del equipo",
    of_count: "de",
    days_unit: "d",
    schedule_1on1: "Programar 1-on-1 →",
    encourage_leave_link: "Fomentar vacaciones →",
    view_details: "Ver detalles →",
    okr_mgmt: "Gestión de OKR",
    okr_subtitle: "Q2 2026 · Seguimiento de objetivos y resultados clave",
    add_okr: "+ Añadir OKR",
    company_okr: "🏢 OKR Empresa",
    team_okr: "👥 OKR Equipo",
    individual_okr: "👤 OKR Individual",
    overall_progress: "Progreso general",
    attendance_linked: "Vinculado a asistencia —",
    actual: "Real",
    usage_rate: "Uso",
    add_individual_okr: "Añadir OKR individual — selecciona un miembro para fijar metas",
    no_okr_set: "Sin OKR definido",
    set_okr: "+ Configurar",
    on_track: "En camino",
    at_risk: "En riesgo",
    off_track: "Fuera de camino",
    team_detail: "Detalles del equipo",
    team_subtitle: "Vista integrada de asistencia × OKR por miembro",
    this_month_sick: "Bajas médicas (mes)",
    okr_progress: "Progreso OKR",
    attendance_mgmt: "Asistencia",
    attendance_subtitle: "Gestiona entradas, salidas y permisos del equipo",
    attendance_calendar: "Calendario de asistencia",
    leave_balance: "Saldo de permisos",
    weekly_attendance: "Asistencia semanal",
    monthly_overtime: "Horas extra (mes)",
    pending_approvals: "Aprobaciones pendientes",
    leave_usage_rate: "Uso de permisos",
    days_remaining: "Días restantes",
    sick_leave: "Baja médica",
    encourage_leave: "Fomentar descanso",
    filter: "Filtrar",
    export_csv: "Exportar CSV",
    global_view: "Vista global integrada",
    global_subtitle: "5 países · 250 personas · Junio 2026",
    headcount: "Personal",
    attendance_rate: "Asistencia",
    avg_overtime: "Horas extra prom.",
    leave_rate: "Uso de permisos",
    compliance_alert_label: "Alerta de cumplimiento",
    compliance_alerts_unit: "",
    compliance_title: "Alertas de cumplimiento",
    monthly_overtime_trend: "Horas extra mensuales promedio por sede",
    ai_analysis: "Análisis IA — Perspectivas de personal",
    ai_analysis_sub: "Recomendaciones basadas en asistencia × logro de OKR",
    view_detail_arrow: "Ver detalles →",
    language: "Idioma de la interfaz",
    timezone: "Zona horaria",
    notification_settings: "Configuración de notificaciones",
    profile: "Perfil",
    save: "Guardar",
    approve: "Aprobar",
    reject: "Rechazar",
    team_health: "Salud del equipo",
    wearable_sync: "Sincronización",
    no_device: "Sin dispositivo",
    health_alert: "Alerta",
    normal: "Normal",
    notif_btn: "Notificaciones",
    unread_count: "Sin leer",
    unread_unit: "",
    mark_all_read: "Marcar todo como leído",
    no_notifications: "Sin notificaciones",
    notif_settings_link: "Configuración de notificaciones →",
    punch_section: "Registro de asistencia",
    punch_in: "Entrada",
    punch_out: "Salida",
    punched_in_at: "En oficina — entrada registrada a las",
    punched_out_at: "Salida registrada. ¡Descansa bien! 👋",
    manual_edit: "Editar manualmente",
    health_saved: "Guardado",
    leave_section: "Solicitud de permiso",
    remaining_leave_label: "Días restantes",
    apply_leave_btn: "Solicitar",
    leave_submitted_msg: "Solicitud enviada. Esperando aprobación.",
    leave_type_label: "Tipo",
    leave_from_label: "Desde",
    leave_to_label: "Hasta",
    leave_reason_label: "Motivo (opcional)",
    leave_submit_btn: "Enviar solicitud",
    cancel_btn: "Cancelar",
    leave_annual: "Vacaciones anuales",
    leave_sick_opt: "Baja por enfermedad",
    leave_special: "Permiso especial",
    leave_half: "Medio día",
    wellness_title: "Chat de bienestar",
    admin_only_label: "Solo visible para admin y tú",
    chat_placeholder: "¿Cómo te sientes hoy?",
    proof_label: "Justificante (captura, nota médica, etc.)",
    upload_btn: "Subir archivo",
    bot_greeting: "¡Hola! Comparte cómo te sientes. Esta conversación solo la ven tú y tu manager. 🔒",
    bot_headache: "Gracias por avisarme. Considera trabajar desde casa o salir antes si lo necesitas. Contacta con RRHH si precisas ayuda.",
    bot_fever: "Si tienes fiebre, evita ir a la oficina. Registra tu temperatura y consulta a un médico si es necesario.",
    bot_tired: "Gracias por compartirlo. La falta de sueño puede afectar tu salud. Considera comunicárselo a tu manager.",
    bot_stress: "Gracias por abrirte. Puedes programar una reunión 1-a-1 en cualquier momento, no dudes en pedirlo.",
    bot_ok: "¡Qué bien! Cuídate y avísame si algo cambia.",
    bot_default: "Gracias por escribir. Si tu estado cambia significativamente, consulta con tu manager o un profesional médico.",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  tData: (base: string, translations?: Partial<Record<string, string>>) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "ja",
  setLang: () => {},
  t: (k) => k,
  tData: (base) => base,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ja");

  useEffect(() => {
    const saved = localStorage.getItem("peopleos_lang") as Lang | null;
    if (saved && T[saved]) setLangState(saved);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("peopleos_lang", l);
  };

  const t = (key: string) => T[lang][key] ?? T["ja"][key] ?? key;

  // Returns translated data string, falling back to Japanese base
  const tData = (base: string, translations?: Partial<Record<string, string>>) => {
    if (!translations || lang === "ja") return base;
    return translations[lang] ?? base;
  };

  return <LangContext.Provider value={{ lang, setLang, t, tData }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
