"use client";

import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "ja" | "en" | "ko" | "vi" | "zh" | "es";

export const LANG_LABELS: Record<Lang, string> = {
  ja: "日本語",
  en: "English",
  ko: "한국어",
  vi: "Tiếng Việt",
  zh: "中文",
  es: "Español",
};

export const LANG_FLAGS: Record<Lang, string> = {
  ja: "🇯🇵",
  en: "🇺🇸",
  ko: "🇰🇷",
  vi: "🇻🇳",
  zh: "🇨🇳",
  es: "🇨🇴",
};

export const T: Record<Lang, Record<string, string>> = {
  ja: {
    // Nav
    dashboard: "ダッシュボード",
    attendance: "勤怠管理",
    okr: "OKR",
    team: "チーム",
    global: "グローバル",
    settings: "設定",
    notifications: "通知設定",
    // Status
    present: "出勤中",
    remote: "在宅勤務",
    leave: "有給休暇",
    absent: "未打刻",
    present_short: "出勤",
    remote_short: "在宅",
    leave_short: "有休",
    absent_short: "未打刻",
    overtime_short: "残業",
    // Dashboard
    greeting: "おはようございます",
    realtime: "リアルタイム",
    team_attendance: "チーム勤怠状況",
    ai_insights: "AI インサイト",
    member: "メンバー",
    status: "ステータス",
    overtime: "今月残業",
    remaining_leave: "残有給",
    team_members_of: "チームメンバー",
    of_count: "名中",
    days_unit: "日",
    schedule_1on1: "1on1をスケジュール →",
    encourage_leave_link: "有給取得を促進 →",
    view_details: "詳細を見る →",
    // OKR page
    okr_mgmt: "OKR 管理",
    okr_subtitle: "Q2 2026 · 目標と主要成果の進捗管理",
    add_okr: "+ OKRを追加",
    company_okr: "🏢 全社 OKR",
    team_okr: "👥 チーム OKR",
    individual_okr: "👤 個人 OKR",
    overall_progress: "総合進捗",
    attendance_linked: "勤怠データ連動 —",
    actual: "実績",
    usage_rate: "消化率",
    add_individual_okr: "個人OKRを追加 — メンバーを選択して目標を設定",
    no_okr_set: "OKR未設定",
    set_okr: "+ 設定する",
    // OKR status
    on_track: "順調",
    at_risk: "要注意",
    off_track: "要改善",
    // Team page
    team_detail: "チーム詳細",
    team_subtitle: "メンバーの勤怠 × OKR 統合ビュー",
    this_month_sick: "病欠（今月）",
    okr_progress: "OKR進捗",
    // Attendance page
    attendance_mgmt: "勤怠管理",
    attendance_subtitle: "チームの出退勤・有給残日数を管理",
    attendance_calendar: "勤怠カレンダー",
    leave_balance: "有給残日数",
    weekly_attendance: "週次勤怠",
    monthly_overtime: "今月残業",
    pending_approvals: "承認待ち申請",
    leave_usage_rate: "有給消化率",
    days_remaining: "残日数",
    sick_leave: "病欠",
    encourage_leave: "取得促進",
    filter: "フィルター",
    export_csv: "CSV出力",
    // Global page
    global_view: "グローバル統合ビュー",
    global_subtitle: "5カ国 · 250名 · 2026年6月",
    headcount: "社員数",
    attendance_rate: "出勤率",
    avg_overtime: "平均残業",
    leave_rate: "有給消化率",
    compliance_alert_label: "法令アラート",
    compliance_alerts_unit: "件",
    compliance_title: "コンプライアンスアラート",
    monthly_overtime_trend: "月次平均残業時間（拠点別推移）",
    ai_analysis: "AI分析 — 人員配置インサイト",
    ai_analysis_sub: "勤怠データ × OKR達成率 から算出した組織への提言",
    view_detail_arrow: "詳細を見る →",
    // Settings
    language: "表示言語",
    timezone: "タイムゾーン",
    notification_settings: "通知設定",
    profile: "プロフィール",
    save: "保存",
    approve: "承認",
    reject: "却下",
    team_health: "チーム健康サマリー",
    wearable_sync: "ウェアラブル連携",
    no_device: "デバイス未連携",
    health_alert: "要確認",
    normal: "正常",
  },
  en: {
    dashboard: "Dashboard",
    attendance: "Attendance",
    okr: "OKR",
    team: "Team",
    global: "Global",
    settings: "Settings",
    notifications: "Notifications",
    present: "In office",
    remote: "Remote",
    leave: "On leave",
    absent: "Not punched",
    present_short: "Present",
    remote_short: "Remote",
    leave_short: "Leave",
    absent_short: "Absent",
    overtime_short: "Overtime",
    greeting: "Good morning",
    realtime: "Real-time",
    team_attendance: "Team Attendance",
    ai_insights: "AI Insights",
    member: "Member",
    status: "Status",
    overtime: "Overtime (mo.)",
    remaining_leave: "Leave left",
    team_members_of: "Team members",
    of_count: "of",
    days_unit: "d",
    schedule_1on1: "Schedule 1-on-1 →",
    encourage_leave_link: "Encourage leave →",
    view_details: "View details →",
    okr_mgmt: "OKR Management",
    okr_subtitle: "Q2 2026 · Track objectives and key results",
    add_okr: "+ Add OKR",
    company_okr: "🏢 Company OKR",
    team_okr: "👥 Team OKR",
    individual_okr: "👤 Individual OKR",
    overall_progress: "Overall progress",
    attendance_linked: "Attendance-linked —",
    actual: "Actual",
    usage_rate: "Usage",
    add_individual_okr: "Add individual OKR — select a member to set goals",
    no_okr_set: "No OKR set",
    set_okr: "+ Set up",
    on_track: "On track",
    at_risk: "At risk",
    off_track: "Off track",
    team_detail: "Team Details",
    team_subtitle: "Attendance × OKR integrated view per member",
    this_month_sick: "Sick days (mo.)",
    okr_progress: "OKR Progress",
    attendance_mgmt: "Attendance",
    attendance_subtitle: "Manage team check-ins and leave balances",
    attendance_calendar: "Attendance Calendar",
    leave_balance: "Leave Balance",
    weekly_attendance: "Weekly Attendance",
    monthly_overtime: "Overtime (month)",
    pending_approvals: "Pending Approvals",
    leave_usage_rate: "Leave usage",
    days_remaining: "Remaining",
    sick_leave: "Sick leave",
    encourage_leave: "Encourage leave",
    filter: "Filter",
    export_csv: "Export CSV",
    global_view: "Global Overview",
    global_subtitle: "5 countries · 250 people · June 2026",
    headcount: "Headcount",
    attendance_rate: "Attendance",
    avg_overtime: "Avg overtime",
    leave_rate: "Leave usage",
    compliance_alert_label: "Compliance alert",
    compliance_alerts_unit: "",
    compliance_title: "Compliance Alerts",
    monthly_overtime_trend: "Monthly avg overtime by location",
    ai_analysis: "AI Analysis — Workforce Insights",
    ai_analysis_sub: "Recommendations derived from attendance × OKR achievement data",
    view_detail_arrow: "View details →",
    language: "Display language",
    timezone: "Timezone",
    notification_settings: "Notification Settings",
    profile: "Profile",
    save: "Save",
    approve: "Approve",
    reject: "Reject",
    team_health: "Team Health Summary",
    wearable_sync: "Wearable sync",
    no_device: "No device",
    health_alert: "Alert",
    normal: "Normal",
  },
  ko: {
    dashboard: "대시보드",
    attendance: "근태 관리",
    okr: "OKR",
    team: "팀",
    global: "글로벌",
    settings: "설정",
    notifications: "알림 설정",
    present: "출근 중",
    remote: "재택근무",
    leave: "유급 휴가",
    absent: "미출근",
    present_short: "출근",
    remote_short: "재택",
    leave_short: "휴가",
    absent_short: "미출근",
    overtime_short: "잔업",
    greeting: "좋은 아침입니다",
    realtime: "실시간",
    team_attendance: "팀 근태 현황",
    ai_insights: "AI 인사이트",
    member: "멤버",
    status: "상태",
    overtime: "이번 달 잔업",
    remaining_leave: "잔여 휴가",
    team_members_of: "팀 멤버",
    of_count: "명 중",
    days_unit: "일",
    schedule_1on1: "1on1 예약하기 →",
    encourage_leave_link: "휴가 촉진하기 →",
    view_details: "자세히 보기 →",
    okr_mgmt: "OKR 관리",
    okr_subtitle: "Q2 2026 · 목표 및 핵심 결과 진행 관리",
    add_okr: "+ OKR 추가",
    company_okr: "🏢 전사 OKR",
    team_okr: "👥 팀 OKR",
    individual_okr: "👤 개인 OKR",
    overall_progress: "종합 진행률",
    attendance_linked: "근태 데이터 연동 —",
    actual: "실적",
    usage_rate: "사용률",
    add_individual_okr: "개인 OKR 추가 — 멤버를 선택하여 목표 설정",
    no_okr_set: "OKR 미설정",
    set_okr: "+ 설정하기",
    on_track: "순조로움",
    at_risk: "주의 필요",
    off_track: "개선 필요",
    team_detail: "팀 상세",
    team_subtitle: "멤버별 근태 × OKR 통합 뷰",
    this_month_sick: "병가 (이번 달)",
    okr_progress: "OKR 진행률",
    attendance_mgmt: "근태 관리",
    attendance_subtitle: "팀 출퇴근 및 휴가 잔여일 관리",
    attendance_calendar: "근태 캘린더",
    leave_balance: "휴가 잔여",
    weekly_attendance: "주간 근태",
    monthly_overtime: "이달 잔업",
    pending_approvals: "승인 대기",
    leave_usage_rate: "휴가 사용률",
    days_remaining: "잔여",
    sick_leave: "병가",
    encourage_leave: "휴가 촉진",
    filter: "필터",
    export_csv: "CSV 내보내기",
    global_view: "글로벌 통합 뷰",
    global_subtitle: "5개국 · 250명 · 2026년 6월",
    headcount: "인원",
    attendance_rate: "출근율",
    avg_overtime: "평균 잔업",
    leave_rate: "휴가 사용률",
    compliance_alert_label: "법령 알림",
    compliance_alerts_unit: "건",
    compliance_title: "컴플라이언스 알림",
    monthly_overtime_trend: "월별 평균 잔업 시간 (거점별 추이)",
    ai_analysis: "AI 분석 — 인력 배치 인사이트",
    ai_analysis_sub: "근태 데이터 × OKR 달성률로 산출한 조직 제언",
    view_detail_arrow: "자세히 보기 →",
    language: "표시 언어",
    timezone: "시간대",
    notification_settings: "알림 설정",
    profile: "프로필",
    save: "저장",
    approve: "승인",
    reject: "거부",
    team_health: "팀 건강 요약",
    wearable_sync: "웨어러블 연동",
    no_device: "기기 없음",
    health_alert: "확인 필요",
    normal: "정상",
  },
  vi: {
    dashboard: "Tổng quan",
    attendance: "Chấm công",
    okr: "OKR",
    team: "Nhóm",
    global: "Toàn cầu",
    settings: "Cài đặt",
    notifications: "Thông báo",
    present: "Đang làm việc",
    remote: "Làm việc từ xa",
    leave: "Nghỉ phép",
    absent: "Chưa chấm công",
    present_short: "Có mặt",
    remote_short: "Từ xa",
    leave_short: "Nghỉ phép",
    absent_short: "Vắng mặt",
    overtime_short: "Tăng ca",
    greeting: "Chào buổi sáng",
    realtime: "Thời gian thực",
    team_attendance: "Chấm công nhóm",
    ai_insights: "AI Insights",
    member: "Thành viên",
    status: "Trạng thái",
    overtime: "Tăng ca (tháng)",
    remaining_leave: "Phép còn lại",
    team_members_of: "Thành viên nhóm",
    of_count: "trong",
    days_unit: "ngày",
    schedule_1on1: "Lên lịch 1-on-1 →",
    encourage_leave_link: "Khuyến khích nghỉ phép →",
    view_details: "Xem chi tiết →",
    okr_mgmt: "Quản lý OKR",
    okr_subtitle: "Q2 2026 · Theo dõi mục tiêu và kết quả then chốt",
    add_okr: "+ Thêm OKR",
    company_okr: "🏢 OKR Công ty",
    team_okr: "👥 OKR Nhóm",
    individual_okr: "👤 OKR Cá nhân",
    overall_progress: "Tiến độ tổng thể",
    attendance_linked: "Liên kết chấm công —",
    actual: "Thực tế",
    usage_rate: "Tỷ lệ",
    add_individual_okr: "Thêm OKR cá nhân — chọn thành viên để đặt mục tiêu",
    no_okr_set: "Chưa có OKR",
    set_okr: "+ Thiết lập",
    on_track: "Đúng tiến độ",
    at_risk: "Cần chú ý",
    off_track: "Cần cải thiện",
    team_detail: "Chi tiết nhóm",
    team_subtitle: "Chấm công × OKR tích hợp theo từng thành viên",
    this_month_sick: "Nghỉ bệnh (tháng)",
    okr_progress: "Tiến độ OKR",
    attendance_mgmt: "Chấm công",
    attendance_subtitle: "Quản lý giờ làm và phép của nhóm",
    attendance_calendar: "Lịch chấm công",
    leave_balance: "Phép còn lại",
    weekly_attendance: "Chấm công tuần",
    monthly_overtime: "Tăng ca (tháng)",
    pending_approvals: "Chờ phê duyệt",
    leave_usage_rate: "Tỷ lệ nghỉ phép",
    days_remaining: "Còn lại",
    sick_leave: "Nghỉ bệnh",
    encourage_leave: "Khuyến khích nghỉ",
    filter: "Lọc",
    export_csv: "Xuất CSV",
    global_view: "Tổng quan toàn cầu",
    global_subtitle: "5 quốc gia · 250 người · Tháng 6/2026",
    headcount: "Nhân sự",
    attendance_rate: "Tỷ lệ đi làm",
    avg_overtime: "Tăng ca TB",
    leave_rate: "Tỷ lệ nghỉ phép",
    compliance_alert_label: "Cảnh báo tuân thủ",
    compliance_alerts_unit: "",
    compliance_title: "Cảnh báo tuân thủ pháp luật",
    monthly_overtime_trend: "Tăng ca trung bình theo tháng (theo chi nhánh)",
    ai_analysis: "Phân tích AI — Insight nhân lực",
    ai_analysis_sub: "Khuyến nghị từ dữ liệu chấm công × tỷ lệ đạt OKR",
    view_detail_arrow: "Xem chi tiết →",
    language: "Ngôn ngữ hiển thị",
    timezone: "Múi giờ",
    notification_settings: "Cài đặt thông báo",
    profile: "Hồ sơ",
    save: "Lưu",
    approve: "Duyệt",
    reject: "Từ chối",
    team_health: "Sức khỏe nhóm",
    wearable_sync: "Đồng bộ thiết bị",
    no_device: "Chưa kết nối",
    health_alert: "Cảnh báo",
    normal: "Bình thường",
  },
  zh: {
    dashboard: "仪表盘",
    attendance: "考勤管理",
    okr: "OKR",
    team: "团队",
    global: "全球",
    settings: "设置",
    notifications: "通知设置",
    present: "在职",
    remote: "远程办公",
    leave: "请假",
    absent: "未打卡",
    present_short: "在勤",
    remote_short: "远程",
    leave_short: "休假",
    absent_short: "未打卡",
    overtime_short: "加班",
    greeting: "早上好",
    realtime: "实时",
    team_attendance: "团队考勤",
    ai_insights: "AI 洞察",
    member: "成员",
    status: "状态",
    overtime: "本月加班",
    remaining_leave: "剩余假期",
    team_members_of: "团队成员",
    of_count: "共",
    days_unit: "天",
    schedule_1on1: "安排1on1 →",
    encourage_leave_link: "促进休假 →",
    view_details: "查看详情 →",
    okr_mgmt: "OKR 管理",
    okr_subtitle: "Q2 2026 · 目标与关键成果进度管理",
    add_okr: "+ 添加 OKR",
    company_okr: "🏢 全司 OKR",
    team_okr: "👥 团队 OKR",
    individual_okr: "👤 个人 OKR",
    overall_progress: "综合进度",
    attendance_linked: "考勤数据关联 —",
    actual: "实绩",
    usage_rate: "使用率",
    add_individual_okr: "添加个人OKR — 选择成员设定目标",
    no_okr_set: "未设置OKR",
    set_okr: "+ 设置",
    on_track: "顺利",
    at_risk: "需关注",
    off_track: "需改善",
    team_detail: "团队详情",
    team_subtitle: "成员考勤 × OKR 综合视图",
    this_month_sick: "病假（本月）",
    okr_progress: "OKR进度",
    attendance_mgmt: "考勤管理",
    attendance_subtitle: "管理团队打卡与假期余额",
    attendance_calendar: "考勤日历",
    leave_balance: "剩余假期",
    weekly_attendance: "本周考勤",
    monthly_overtime: "本月加班",
    pending_approvals: "待审批",
    leave_usage_rate: "假期使用率",
    days_remaining: "剩余",
    sick_leave: "病假",
    encourage_leave: "鼓励休假",
    filter: "筛选",
    export_csv: "导出 CSV",
    global_view: "全球综合视图",
    global_subtitle: "5个国家 · 250人 · 2026年6月",
    headcount: "人数",
    attendance_rate: "出勤率",
    avg_overtime: "平均加班",
    leave_rate: "假期使用率",
    compliance_alert_label: "合规警报",
    compliance_alerts_unit: "件",
    compliance_title: "合规警报",
    monthly_overtime_trend: "各据点月均加班时间趋势",
    ai_analysis: "AI分析 — 人力配置洞察",
    ai_analysis_sub: "基于考勤数据 × OKR达成率的组织建议",
    view_detail_arrow: "查看详情 →",
    language: "显示语言",
    timezone: "时区",
    notification_settings: "通知设置",
    profile: "个人资料",
    save: "保存",
    approve: "批准",
    reject: "拒绝",
    team_health: "团队健康摘要",
    wearable_sync: "可穿戴设备同步",
    no_device: "未连接设备",
    health_alert: "需关注",
    normal: "正常",
  },
  es: {
    dashboard: "Panel",
    attendance: "Asistencia",
    okr: "OKR",
    team: "Equipo",
    global: "Global",
    settings: "Configuración",
    notifications: "Notificaciones",
    present: "En oficina",
    remote: "Remoto",
    leave: "Permiso",
    absent: "Sin registrar",
    present_short: "Presente",
    remote_short: "Remoto",
    leave_short: "Permiso",
    absent_short: "Sin registrar",
    overtime_short: "Extra",
    greeting: "Buenos días",
    realtime: "Tiempo real",
    team_attendance: "Asistencia del equipo",
    ai_insights: "Perspectivas de IA",
    member: "Miembro",
    status: "Estado",
    overtime: "Horas extra (mes)",
    remaining_leave: "Días restantes",
    team_members_of: "Miembros del equipo",
    of_count: "de",
    days_unit: "d",
    schedule_1on1: "Programar 1-on-1 →",
    encourage_leave_link: "Fomentar vacaciones →",
    view_details: "Ver detalles →",
    okr_mgmt: "Gestión de OKR",
    okr_subtitle: "Q2 2026 · Seguimiento de objetivos y resultados clave",
    add_okr: "+ Añadir OKR",
    company_okr: "🏢 OKR Empresa",
    team_okr: "👥 OKR Equipo",
    individual_okr: "👤 OKR Individual",
    overall_progress: "Progreso general",
    attendance_linked: "Vinculado a asistencia —",
    actual: "Real",
    usage_rate: "Uso",
    add_individual_okr: "Añadir OKR individual — selecciona un miembro para fijar metas",
    no_okr_set: "Sin OKR definido",
    set_okr: "+ Configurar",
    on_track: "En camino",
    at_risk: "En riesgo",
    off_track: "Fuera de camino",
    team_detail: "Detalles del equipo",
    team_subtitle: "Vista integrada de asistencia × OKR por miembro",
    this_month_sick: "Bajas médicas (mes)",
    okr_progress: "Progreso OKR",
    attendance_mgmt: "Asistencia",
    attendance_subtitle: "Gestiona entradas, salidas y permisos del equipo",
    attendance_calendar: "Calendario de asistencia",
    leave_balance: "Saldo de permisos",
    weekly_attendance: "Asistencia semanal",
    monthly_overtime: "Horas extra (mes)",
    pending_approvals: "Aprobaciones pendientes",
    leave_usage_rate: "Uso de permisos",
    days_remaining: "Días restantes",
    sick_leave: "Baja médica",
    encourage_leave: "Fomentar descanso",
    filter: "Filtrar",
    export_csv: "Exportar CSV",
    global_view: "Vista global integrada",
    global_subtitle: "5 países · 250 personas · Junio 2026",
    headcount: "Personal",
    attendance_rate: "Asistencia",
    avg_overtime: "Horas extra prom.",
    leave_rate: "Uso de permisos",
    compliance_alert_label: "Alerta de cumplimiento",
    compliance_alerts_unit: "",
    compliance_title: "Alertas de cumplimiento",
    monthly_overtime_trend: "Horas extra mensuales promedio por sede",
    ai_analysis: "Análisis IA — Perspectivas de personal",
    ai_analysis_sub: "Recomendaciones basadas en asistencia × logro de OKR",
    view_detail_arrow: "Ver detalles →",
    language: "Idioma de la interfaz",
    timezone: "Zona horaria",
    notification_settings: "Configuración de notificaciones",
    profile: "Perfil",
    save: "Guardar",
    approve: "Aprobar",
    reject: "Rechazar",
    team_health: "Salud del equipo",
    wearable_sync: "Sincronización",
    no_device: "Sin dispositivo",
    health_alert: "Alerta",
    normal: "Normal",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  tData: (base: string, translations?: Partial<Record<string, string>>) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "ja",
  setLang: () => {},
  t: (k) => k,
  tData: (base) => base,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ja");

  useEffect(() => {
    const saved = localStorage.getItem("peopleos_lang") as Lang | null;
    if (saved && T[saved]) setLangState(saved);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("peopleos_lang", l);
  };

  const t = (key: string) => T[lang][key] ?? T["ja"][key] ?? key;

  // Returns translated data string, falling back to Japanese base
  const tData = (base: string, translations?: Partial<Record<string, string>>) => {
    if (!translations || lang === "ja") return base;
    return translations[lang] ?? base;
  };

  return <LangContext.Provider value={{ lang, setLang, t, tData }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
